apiVersion: v1
kind: Service
metadata:
  name: service-document
  namespace: mineco-dev
  labels:
    app.kubernetes.io/name: documentos
    app.kubernetes.io/part-of: documentos
  annotations:
    metallb.universe.tf/address-pool: production-public-ips
spec:
  type: LoadBalancer
  externalIPs:
  - 128.5.9.77
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: smtp
      port: 25
      targetPort: 25
      protocol: TCP
    - name: smtp-587
      port: 587
      targetPort: 587
      protocol: TCP
  selector:
    run: laravel-documentos
